apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: mongo
  name: mongo-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: mongo
    spec:
      containers:
      - name: mongo
        image: gcr.io/marshallpowell/mongo-server:latest
        env:
        - name: MONGO_DB_NAME
          value: twangband
        - name: ADMIN_MONGO_DB_USER
          valueFrom:
            secretKeyRef:
              name: twangband-secrets
              key: admin-mongodb-user
        - name: ADMIN_MONGO_DB_PASS
          valueFrom:
            secretKeyRef:
              name: twangband-secrets
              key: admin-mongodb-pass
        - name: TB_MONGO_DB_USER
          valueFrom:
            secretKeyRef:
              name: twangband-secrets
              key: tb-mongodb-user
        - name: TB_MONGO_DB_PASS
          valueFrom:
            secretKeyRef:
              name: twangband-secrets
              key: tb-mongodb-pass
        ports:
        - name: mongo
          containerPort: 27017
          hostPort: 27017
        volumeMounts:
            - name: mongo-persistent-storage
              mountPath: /data/db
      volumes:
        - name: mongo-persistent-storage
          gcePersistentDisk:
            pdName: prod-mongodb-disk
            fsType: ext4