apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: web
  name: web-controller
spec:
  replicas: 1
  selector:
    name: web
  template:
    metadata:
      labels:
        name: web
    spec:
      containers:
      - name: web
        image: gcr.io/marshallpowell/twang-web:latest
        env:
        - name: FB_CLIENTID
          value: '1558893454364234'
        - name: FB_CALLBACKURL
          value: https://twangband.com/auth/facebook/callback
        - name: FB_CLIENTSECRET
          value: 1992cb3d2ab570277129e9f8911b63a4
        - name: BASE_URL
          value: http://twangband.com
        - name: DISQUS_API_SECRET
          value: o0gPCh8Z0pMaoHe7ZQpHXTTkPDr8sizCQdtuReaOhTSE3gJJQQ7Z5Rwo3Rz2WNpm
        - name: DISQUS_API_PUBLIC_KEY
          value: MQsaIfAKop1vGYWcFYcL45ScnhzQ5L5h74IxnzTUe9ovGArKHHRfxMZ5jLx19f4W
        - name: MONGO_URL
          value: mongo
        - name: MONGO_DB_NAME
          value: twangband
        - name: LOG_DIR
          value: /logs/
        - name: UPLOADS_DIR
          value: /uploads/
        - name: UPLOADS_BUCKET
          value: prod-twangband
        - name: TB_MONGO_DB_USER
          valueFrom:
            secretKeyRef:
              name: twangband-secrets
              key: tb-mongodb-user
        - name: TB_MONGO_DB_PASS
          valueFrom:
            secretKeyRef:
              name: twangband-secrets
              key: tb-mongodb-pass
        ports:
        - containerPort: 3000
          name: http-server
        securityContext:
          privileged: true
