apiVersion: v1
kind: Service
metadata:
  name: websocket
  labels:
    name: websocket
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3001
      protocol: TCP
  selector:
    name: websocket