apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: websocket
  name: websocket-controller
spec:
  replicas: 1
  selector:
    name: websocket
  template:
    metadata:
      labels:
        name: websocket
    spec:
      containers:
      - name: websocket
        image: gcr.io/marshallpowell/twang-web:latest
        env:
        - name: ENABLE_WEBSOCKETS
          value: 'true'
        - name: MONGO_URL
          value: mongo
        - name: MONGO_DB_NAME
          value: twangband
        - name: LOG_DIR
          value: /logs/
        - name: UPLOADS_DIR
          value: /uploads/
        - name: UPLOADS_BUCKET
          value: dev-twangband
        - name: TB_MONGO_DB_USER
          valueFrom:
            secretKeyRef:
              name: twangband-secrets
              key: tb-mongodb-user
        - name: TB_MONGO_DB_PASS
          valueFrom:
            secretKeyRef:
              name: twangband-secrets
              key: tb-mongodb-pass
        ports:
        - containerPort: 3001
          name: http-server
        securityContext:
          privileged: true
