apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-ssl-proxy
  labels:
    name: nginx
    role: ssl-proxy
spec:
  replicas: 1
  selector:
    name: nginx
    role: ssl-proxy
  template:
    metadata:
      name: nginx-ssl-proxy
      labels:
        name: nginx
        role: ssl-proxy
    spec:
      containers:
      - name: nginx
        image: gcr.io/marshallpowell/nginx-ssl-proxy:latest
        command:
        - /bin/bash
        - ./start.sh
        env:
        - name: SERVICE_HOST_ENV_NAME
          value: WEB_SERVICE_HOST
        - name: SERVICE_PORT_ENV_NAME
          value: WEB_SERVICE_PORT
        - name: CDN_TARGET_SERVICE
          value: storage.googleapis.com
        - name: CDN_TARGET_PATH
          value: dev-twangband
        - name: WEBSOCKET_SERVICE_HOST_ENV_NAME
          value: WEBSOCKET_SERVICE_HOST
        - name: WEBSOCKET_SERVICE_PORT_ENV_NAME
          value: WEBSOCKET_SERVICE_PORT
        - name: ENABLE_SSL
          value: 'true'
        - name: ENABLE_BASIC_AUTH
          value: 'false'
        ports:
        - name: ssl-proxy-http
          containerPort: 80
        - name: ssl-proxy-https
          containerPort: 443
        volumeMounts:
        - name: secrets
          mountPath: /etc/secrets
          readOnly: true
      volumes:
      - name: secrets
        secret:
          secretName: twangband-secrets