var logger = require(APP_LIB + 'util/Logger').getLogger(__filename);
var TagDao = module.exports = {};


/////////////////////////////////////
var instruments = [
    "Accordion",
    "Acoustic bass guitar",
    "Acoustic guitar",
    "Acoustic bass guitar",
    "Aeolian harp",
    "Agung a Tamlang) (Philippine slit drum)",
    "Agung/ agong (Philippine gong)",
    "Ahoko (Ivory Coast rattle)",
    "Ajaeng",
    "Alboka (Spanish double hornpipe)",
    "Alphorn",
    "Alpine bell",
    "Alto clarinet",
    "Alto flute",
    "Alto horn",
    "Alto sarrusophone",
    "Alto saxophone",
    "Angklung (tuned bamboo slide rattle)",
    "Appalachian dulcimer",
    "Archlute",
    "Arghul (Arabic double pipe)",
    "Arpa anottolini (Italian hooked harp)",
    "Arpeggione (Italian six-string)",
    "Array Mbira (African thumb piano)",
    "Aru-ding (Philippine Jew’s harp)",
    "Aulochrome (double soprano saxophone)",
    "Babendil (Philippine gong)",
    "Baglama/ saz (Turkish strings)",
    "Balafon (xylophone from Ghana)",
    "Balalaika (Central Asian 2 or 3 stringed guitar)",
    "Bandola (plucked lute from Cuba, Chile and Peru)",
    "Bandoneón (Argentinian concertina)",
    "Bandurria (Spanish/ Latin American plucked lute)",
    "Banhu (Chinese bowed stringed instrument)",
    "Banjo",
    "Barbat (Iranian plucked lute)",
    "Baritone horn",
    "Baritone sarrusophone",
    "Baritone saxophone",
    "Baroque Wooden Flute",
    "Baryton (German Euphonium)",
    "Bass Clarinet",
    "Bass Drum",
    "Bass flute",
    "Bass guitar",
    "Bass sarrusophone",
    "Bass saxophone",
    "Bass/ baritone oboe",
    "Basse a Pistons (French Euphonium)",
    "Basse Cor",
    "Basset clarinet",
    "Basset horn",
    "Bassoon",
    "Bawu (Chinese wind instrument)",
    "Bayan (Russian Accordian)",
    "Bazooka",
    "Bell",
    "Berimbao (Brazilian musical bow)",
    "Bianqing (Chinese stone chimes)",
    "Bianzhong (Chinese bells)",
    "Bifora (Sicillian oboe)",
    "Biniou (French bagpipe)",
    "Biwa (Japanese short-necked lute)",
    "Bock (German bagpipes)",
    "Bodega (French bagpipe)",
    "Bodhrán (Irish drum)",
    "Boha (French bagpipe)",
    "Bombarde",
    "Bombardino (Spanish Euphonium)",
    "Bongo drum",
    "Border pipe/ lowland bagpipe",
    "Bordonua (Puerto Rican bass guitar)",
    "Bouzouki (Greek lute)",
    "Brian Boru bagpipes",
    "Bullroarer",
    "Button accordian",
    "Cabrette (French bagpipe)",
    "Calliope (steam organ)",
    "Carillon (Dutch harmonising bells)",
    "Carillon (Dutch harmonising bells)",
    "Castanets",
    "Cavaco (Spanish guitar)",
    "Cavaquinho (Portuguese guitar)",
    "Caxixi (Brazilian idiophone)",
    "Celesta (idiophone) invented 1886 in Paris by Auguste Mustel.",
    "Cello",
    "Ceng (Turkish harp)",
    "Chabrette (French bagpipe)",
    "Chapman stick (fretboard)",
    "Charango (South American fretted lute)",
    "Chenda (Indian drum)",
    "Chi (Chinese Transverse Flute)",
    "Chimes",
    "Ching (Cambodian/ Thai finger cymbals)",
    "Chitaronne (lower-toned lute)",
    "Chitarra battebte (Italian guitar)",
    "Chromatic accordian",
    "Cigar box guitar",
    "Cimbalom (Eastern European hammered dulcimer)",
    "Cimbasso",
    "Cimpoi (Romanian bagpipe)",
    "Cittern (Renaissance lute)",
    "Clapped hands",
    "Clarinet",
    "Clarinette d’amour",
    "Classical guitar",
    "Clavicembelo (Italian pianoforte)",
    "Clavichord",
    "Clavichord (European stringed keyboard)",
    "Concertina",
    "conch",
    "Conga (Caribbean drum)",
    "Contra-alto clarinet",
    "Contra-alto flute",
    "Contrabass á anche",
    "Contrabass clarinet",
    "Contrabass flute",
    "Contrabass oboe",
    "Contrabass Sarrusophone",
    "Contrabass saxophone",
    "Contrabassoon",
    "Cornet/ Cornett/ Cornetto/ Zink",
    "Cornish bagpipes",
    "Cowbell",
    "Croatian bagpipes",
    "Cromorne",
    "Crotales (Struck cymbals)",
    "Crumhorn",
    "Crwth (Welsh stringed instrument)",
    "Cuatro (Latin American lute)",
    "Cuíca (Brazilian drum)",
    "Cymbals – crash, hi-hat, ride, splash, tom-toms, zil",
    "Cymbalum (Western European hammered dulcimer)",
    "Da’uli da’uli (Indonesian xylophone)",
    "Dabakan (Philippine drum)",
    "Dadihu (contrabass erhu)",
    "Dahu (Chinese bowed stringed instrument)",
    "Daiko (Japanese drum)",
    "Dankiyo (Turkish bagpipe)",
    "Daraboukka (Syrian drum)",
    "Darabukka (Arabic drum)",
    "Darbuka (Greek drum)",
    "Darvyra (Greek Duct Flute)",
    "Denis d’or (ancient Czech chordophone)",
    "Dhol (Iranian drum)",
    "Dholak (North Indian hand drum)",
    "Didgeridoo (Aboriginal Natural Trumpet)",
    "Dihu (Chinese large bowed stringed instrument)",
    "Diyingehu (contrabass gehu)",
    "Djembe (West African hand drum)",
    "Doedelzak (Dutch bagpipe)",
    "Dombak (Iranian drum)",
    "Domra (Russian mandolin)",
    "Dotara (bass ektara)",
    "Double Bass",
    "Double contrabass flute",
    "Doulophone/ cuprophone",
    "Drum machine",
    "Dubreq stylophone",
    "Duct Flute",
    "Dudelsack (German bagpipe)",
    "Dudy (Czech bagpipes)",
    "Duff (Islamic tambourine)",
    "Dulcian (pre-1700’s Western European Bassoon)",
    "Dulcimer (hammered zither)",
    "Dulzaina (Spanish oboe)",
    "Dumbelek (Turkish drum)",
    "Dun dun (West African large talking drum)",
    "Dutar (Central Asian lute)",
    "Duxianqin (Chinese one-stringed zither)",
    "Ektara (Indian one-string)",
    "Electric guitar",
    "Electric organ",
    "Electric piano",
    "Electronic:",
    "English Horn/ Cor Anglais (French tenor Oboe)",
    "Erhu (Chinese violin)",
    "Erxian (Chinese bowed stringed instrument)",
    "Euphonium",
    "Fangxiang (Chinese metallophone)",
    "Fiddle",
    "Finger Cymbals",
    "Fingerboard synthesizer",
    "Fiscarmonica (Italian Accordian)",
    "Flageolets",
    "Flugelhorn",
    "Flute",
    "Folgerphone",
    "French Horn",
    "Gaida (Southern Balkan bagpipes)",
    "Gaita (Portuguese & Spanish bagpipe)",
    "Gajdy (Eastern European bagpipes)",
    "Gambang (Indonesian xylophone)",
    "Gan gan (West African small talking drum)",
    "Gandingan (Philippine set of 4 hanging gongs)",
    "Gandingan a kayo (Philippine xylophone)",
    "Ganza (Brazilian rattle)",
    "Gaohu (Chinese bowed stringed instrument)",
    "Gayageum (Korean zither)",
    "Gehu (Chinese cello-like)",
    "Gender (Indonesian brass xylophone)",
    "Geomungo/ komungo (Korean zither)",
    "Ghatam (Indian drum)",
    "Glass marimba",
    "Glasschord (crystallophone)",
    "Glockenspiel",
    "Gong",
    "Gottuvadhyam (Indian 21-stringed guitar)",
    "Great Highland bagpipe",
    "Great Irish warpipes",
    "Guan (Chinese pipe)",
    "Gugin (Chinese bridgeless zither)",
    "Guiro (South/Central American notched gourd)",
    "Guitar",
    "Guitar 12 Strings",
    "Guitarrón",
    "Guqin (Chinese plucked zither)",
    "Gusle/ gusla (Balkan guitar)",
    "Gusli (Russian harp)",
    "Guzheng (Chinese zither)",
    "Hammered dulcimer",
    "Handbells",
    "Hang (steel hand drum)",
    "Hardanger fiddle",
    "Harmonica/ Mouth Organ",
    "Harmonium/ reed organ",
    "Harp",
    "Harp guitar",
    "Harpsichord",
    "Heckelphone",
    "Hegelong (Philippine fretted boat-lute)",
    "Hélicon",
    "Hichiriki (Japanese Oboe)",
    "Hocchiku (Japanese flute)",
    "Hooked harp",
    "Horagai (Japanese conch)",
    "Horn",
    "Hosho (Zimbabwean rattle)",
    "Hsaio (Chinese Duct Flute)",
    "Huemmelchen (German smallpipes)",
    "Huluhu (Chinese bowed stringed instrument)",
    "Hun (Korean flute)",
    "Hunting Horn",
    "Huqin (Chinese bowed stringed instrument)",
    "Hurdy Gurdy",
    "Igil (Tuvan bowed instrument)",
    "Inci (Philippine flute)",
    "Ipu (Hawaiian rattle)",
    "Irish bouzouki",
    "Irish Uilleann (Indoor bagpipe)",
    "Istarski mih (Croatian bagpipe)",
    "Janggu (Korean drum)",
    "Japanese Bamboo Flute/ Shakuhachi",
    "Jew’s harp",
    "Jew’s harp (plucked idiophone)",
    "Jiaohu (Chinese bowed stringed instrument)",
    "Jinghu (Chinese bowed stringed instrument)",
    "Jug",
    "Kadlong (Philippine fretted boat-lute)",
    "Kagul (Philippine slit drum)",
    "Kangling (Tibetan serunai)",
    "Kaval (Slovakian Duct Flute)",
    "Kèn b?u (Vietnamese reed)",
    "Kettle drum/ Timpani",
    "Keyed Bugle",
    "Keyed Trumpet",
    "Khene (Northeast Thailand mouth organ)",
    "Khim (Cambodian/ Thai hammered dulcimer)",
    "Khloy (Cambodian flute)",
    "Khol (South Indian drum)",
    "Kissar (West African lyre)",
    "Knatele (Finnish zither)",
    "Kokyu (Japanese bowed instrument)",
    "Komungo (Korean zither)",
    "Kora (West African 21-string harp-lute)",
    "Koto (Japanese zither)",
    "Koudi (Chinese flute)",
    "Koziol (Polish bagpipe)",
    "Kubing (Philippine Jew’s harp)",
    "Kulintang a kayo (Philippine xylophone)",
    "Kulintang a putao/ kulintang a tiniok (Philippine metallophone)",
    "Kulintang/ kolintang (Philippine gong group)",
    "Kutiyapi (Philippine fretted boat-lute)",
    "Kwa-yen (Chinese hanging drum)",
    "Kwintangen kayo/ luntang (Philippine xylophone)",
    "Lambeg (Irish drum)",
    "Lancashire great-pipe",
    "Langeleik (Norwegian stringed instrument)",
    "Laruan (Chinese stringed instrument)",
    "Lasso d’amore",
    "Launeddas (Sardinian triple clarinet)",
    "Leier (German hurdy gurdy)",
    "Leiqin (Chinese bowed instrument)",
    "Lirone",
    "Lithophone (stone barred xylophone)",
    "Lusheng (Chinese bamboo pipes)",
    "Lute",
    "Lyre",
    "Magyar duda (Hungarian bagpipes)",
    "Maguhu (Chinese bowed stringed instrument)",
    "Malimba (xylophone from the Congo)",
    "Mando-bass (bass mandolin)",
    "Mandocello (large mandolin)",
    "Mandola (US/ Canadian fretted stringed instrument)",
    "Mandolin",
    "Mangtong (Chinese bamboo pipes)",
    "Maraca",
    "Marimba",
    "Marimbao (Brazilian stringed instrument)",
    "Marinbaphone",
    "Mbira/ Sanza/ Thumb Piano (African stringed instrument)",
    "Mellophone",
    "Mellotron (polyphonic keyboard)",
    "Melodeon",
    "Melodica",
    "Metallophones (metal barred xylophone)",
    "Mijwiz (Arabic double pipe)",
    "Mittlealtersackpfeife (German medieval bagpipe)",
    "Mizwad (Arabic bagpipe)",
    "Mohan veena (Indian guitar)",
    "Moodswinger (zither)",
    "Morin khuur/ morin huur (Mongolian fiddle)",
    "Mridangam (South Indian drum)",
    "Muchosac (Belgian bagpipe)",
    "Musette bressane (French bagpipe)",
    "Musette de cour (French bagpipe)",
    "Musette du centre (French bagpipe)",
    "Musical bow",
    "Musical Saw (wood cutting saw)",
    "Nadaswaram (Indian wind instrument)",
    "Naqara (Mongolian war drum)",
    "Natural Trumpet",
    "Nay (Syrian wooden flute)",
    "Ney (Lebanese Flute)",
    "Northumbrian smallpipes",
    "Nose flute",
    "Nyckelharpa (Swedish key harp)",
    "Oboe",
    "Oboe d’amore",
    "Oboe da caccia",
    "Ocarina",
    "Octaban (cylinder drum)",
    "Octapad (electronic drumpad)",
    "Octave mandolin",
    "Octavin",
    "Octocontra-alto clarinet",
    "Octocontrabass clarinet",
    "Oliphant/ Cor d’Oliphant",
    "Ondes martenot (electronic keyboard and slide)",
    "Ophicleide",
    "Organ - electric",
    "Organ pipe",
    "Overtone guitar",
    "Paixiao (Chinese flute)",
    "Palendang (Philippine flute)",
    "Pan pipes",
    "Pastoral pipes",
    "Piano",
    "Piccolo",
    "Piccolo clarinet",
    "Piccolo heckelphone",
    "Piccolo oboe",
    "Pipa (Chinese lute)",
    "Pipe organ",
    "Piva (Northern Italian bagpipe)",
    "Psaltery (plucked zither)",
    "Pulalu (Philippine flute)",
    "Qanun (Turkish zither)",
    "Quena (Andean flute)",
    "Quinticlave (Ophicleide)",
    "Racket",
    "Rainstick",
    "Raita (Moroccan serunai)",
    "Rajao (Portuguese guitar)",
    "Ranat ek elk (Thai metallophone)",
    "Ranat thum lek (Thai metallophone)",
    "Ratchet",
    "Rattle",
    "Rebab (Arabic bowed stringed instrument)",
    "Rebec (15th/ 16th century rebab)",
    "Recorder (Descant)",
    "Reed contrabass",
    "Reed Pipe",
    "Riq/ riqq/ rik (Arabic tambourine)",
    "Roman tuba",
    "Ruan (Chinese plucked stringed instrument)",
    "Rudra veena (Indian plucked stringed instrument)",
    "Ryuteki (Japanese flute)",
    "Sabar (Senegalese drum)",
    "Sac de gemecs (Catalonian bagpipe)",
    "Sackbutt (trombone family’s ancestor)",
    "Säckpipa (Swedish bagpipe)",
    "Saenghwang (Korean mouth organ)",
    "Sallaneh (Iranian plucked stringed instrument)",
    "Sampho (Cambodian barrel drum)",
    "Sampler",
    "Sang-auk (Burmese harp)",
    "Santur (North Indian hammered zither)",
    "Sanxian (Chinese lute)",
    "Saraswati veena (South Indian lute)",
    "Sarrusophone",
    "Sarunay/ saronay/ sarunai/ saronai (Philippine metallophone)",
    "Saung (Burmese harp)",
    "Saw ou (Thai bowed stringed instrument)",
    "Saw sam sai (Thai bowed stringed instrument)",
    "Saxhorn",
    "Saxonette",
    "Saxophone",
    "Schweizer sackpfeife (Swiss bagpipe)",
    "Scottish smallpipes",
    "Se (Chinese zither)",
    "Serpent",
    "Serunai (Islamic reed instrument)",
    "Setar (Iranian lute)",
    "Shamisen (Japanese 3-stringed instrument)",
    "Shawm (Renaissance oboe)",
    "Shekere (African rattle)",
    "Sheng (Chinese mouth organ)",
    "Shinobue (Japanese flute)",
    "Shofar (Jewish horn)",
    "Sihu (Chinese bowed stringed instrument)",
    "Singing bowl/ rin gong (Himalayan standing bell)",
    "Siren",
    "Sitar (South Asian lute)",
    "Sleigh Bells",
    "Slide guitar",
    "Slide whistle",
    "Slit drum",
    "Snare Drum",
    "Sopranino clarinet",
    "Sopranino saxophone",
    "Soprano clarinet",
    "Soprano mandolin",
    "Soprano saxophone",
    "soprillo",
    "Sorna (Afghan serunai)",
    "Sousaphone",
    "Spoons",
    "Sralai (Cambodian reed)",
    "Steel drum",
    "Steel guitar",
    "Subcontrabass flute",
    "Subcontrabass saxophone",
    "Suling (Indonsian/Philippine flute)",
    "Suona (Chinese serunai)",
    "Synclavier",
    "Synthesizer",
    "Tabla (Indian/ Pakistani drum)",
    "Tagutok (Philippine slit drum)",
    "Taiko (Japanese drum)",
    "Talking drum",
    "Tambour (French drum)",
    "Tambourine",
    "Tamburitza (Croatian/ Serbian mandolin)",
    "Tan-tan (Brazilian hand drum)",
    "Taphon (Thai drum)",
    "Tar (Persian lute)",
    "Tárogató (Hungarian shawm)",
    "Tea chest bass (skiffle bass)",
    "Tenor horn",
    "Tenor mandola (European/ UK fretted stringed instrument)",
    "Tenor sarrusophone",
    "Tenor saxophone",
    "Tenoroon (tenor bassoon)",
    "Teponaztli (Mexican wooden drum)",
    "Thavil (Indian drum)",
    "Theorbo (lower-toned lute)",
    "Theremin (oscillator)",
    "Timpani/ kettle drum",
    "Timple (Canary Islands/ Murcia ukulele)",
    "Tin whistle",
    "Tjelempung/ Celempung (Javanese zither)",
    "Tom-tom",
    "Tonette (plastic recorder)",
    "Torupill (Estonian bagpipe)",
    "Transverse Flute (Traditional Flute)",
    "Trekspill (Norwegian Accordian)",
    "Tres (Cuban chordophone)",
    "Triangle",
    "Tro u (Cambodian bowed stringed instrument)",
    "Tromba marina (European stringed instrument)",
    "Trombone",
    "Tromboon/ babone",
    "Trompeta china (Cuban suona)",
    "Trumpet",
    "Trumpet Bb",
    "Tsampouna (Greek bagpipe)",
    "Tsuri-daiko (Japanese hanging drum)",
    "Tuba",
    "Tubular Bells",
    "Tuhu (Chinese bowed stringed instrument)",
    "Tulum (Turkish bagpipe)",
    "Tumpong (Philippine flute)",
    "Turntables",
    "Ud/ oud (Arabic and Islamic lute)",
    "Udu (African clay drum)",
    "Ukulele (Hawaiian guitar)",
    "Valiha (Indonesian and Madagascan zither)",
    "Vertical flute",
    "Vertical viola",
    "Veuze (French bagpipe)",
    "Vibraphone/ vibraharp",
    "Vichitra veena (Indian stringed instrument)",
    "Vielle (French hurdy gurdy)",
    "Vihuela (Spanish 2-string guitar)",
    "Viola",
    "Viola d’amore",
    "Viola da gamba",
    "Viola organista",
    "Violin",
    "Violotta",
    "Vladimirsky Rozhok",
    "Volinka (Russian bagpipes)",
    "Wagner Tuba",
    "Washboard",
    "Washint (Ethiopian flute)",
    "Washtub bass",
    "Welsh pipes",
    "Whip",
    "Whistle",
    "Willow flute",
    "Wind Chimes",
    "Xalam/ khalam (West African Banjo-like instrument)",
    "Xiao (Chinese flute)",
    "Xiaodihu (tenor erhu)",
    "Xun (Chinese flute)",
    "Xylophone",
    "Xylorimba (extended range xylophone)",
    "Yang chi’in (Chinese zither)",
    "Yang Chin (Chinese hammered dulcimer)",
    "Yayli tanbur (Turkish lute)",
    "Yazheng (Chinese zither)",
    "Yehu (Chinese bowed stringed instrument)",
    "Yu (Chinese bamboo pipes)",
    "Yueh Ch’in (Chinese lute)",
    "Yun Lo (Chinese gong)",
    "Zampogna (Italian bagpipe)",
    "Zaqq (Maltese bagpipe)",
    "Zhongdihu (bass erhu)",
    "Zhuihu (Chinese bowed stringed instrument)",
    "Zither",
    "Zonghu (Chinese bowed stringed instrument)",
    "Zufalo (Italian flute)",
    "Zurna (Turkish serunai)"];



////////////////////////////////////





TagDao.getInstruments = function(){

    return instruments;
}

